ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'TOEIC_QUESTION_RESPONSE';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'TOEIC_CONVERSATIONS';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'TOEIC_TALKS';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'TOEIC_INCOMPLETE_SENTENCES';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'TOEIC_TEXT_COMPLETION';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'TOEIC_READING_COMPREHENSION';
