ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'READING_SHORT';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'READING_MEDIUM';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'READING_LONG';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'READING_INTEGRATED';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'READING_ARGUMENT';
ALTER TYPE "QuestionType" ADD VALUE IF NOT EXISTS 'READING_INFORMATION';
